# Generated by Django 5.1.1 on 2024-09-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
