# Generated by Django 5.1.1 on 2024-09-28 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_friendship_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
