# Generated by Django 5.1.1 on 2024-10-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('S', 'Started'), ('F', 'Finished')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_player1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_player2',
            field=models.IntegerField(null=True),
        ),
    ]
