# Generated by Django 5.1.1 on 2024-10-18 13:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_match_status_alter_match_score_player1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
