# Generated by Django 5.1.1 on 2024-10-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_match_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='score_player1',
            new_name='player1_score',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='score_player2',
            new_name='player2_score',
        ),
        migrations.AddField(
            model_name='match',
            name='forfeited',
            field=models.BooleanField(default=False),
        ),
    ]
