# Generated by Django 5.1.1 on 2024-10-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_rename_score_player1_match_player1_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='draw',
            field=models.BooleanField(default=False),
        ),
    ]
