# Generated by Django 5.1.1 on 2024-10-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_match_draw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='draw',
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('S', 'Started'), ('F', 'Finished'), ('C', 'Canceled')], default='P', max_length=1),
        ),
    ]
