# Generated by Django 5.1.1 on 2024-09-28 17:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='friend_requests',
            field=models.ManyToManyField(related_name='friend_requests_from', to=settings.AUTH_USER_MODEL),
        ),
    ]
