# Generated by Django 5.1.1 on 2024-10-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0004_remove_customuser_friend_requests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
    ]
