# Generated by Django 5.1.1 on 2024-10-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0005_customuser_is_connected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_connected',
        ),
        migrations.AddField(
            model_name='customuser',
            name='connection_counter',
            field=models.IntegerField(default=0),
        ),
    ]
